-- SENTENCIA PARA INGRESAR 2 USUARIOS EN LA TABLA usuarios


-- SENTENCIA PARA INGRESAR 6 PRODUCTOS EN LA TABLA productos


-- SENTENCIA PARA INGRESAR 6 INGREDIENTES EN LA TABLA ingredientes


-- SENTENCIA PARA INGRESAR 6 REGISTROS EN LA TABLA listaingredientes


-- SENTENCIA PARA INGRESAR 6 PEDIDOS EN LA TABLA pedidos


-- SENTENCIA PARA INGRESAR 6 REGISTROS EN LA TABLA detallespedido